version: '3.7'

services:
  nginx:
    image: meu-nginx-tls13
    restart: always
    ports:
      - 8080:80    # Para acessar via HTTP
      - 8443:443   # Para acessar via HTTPS
    volumes:
      - ./joomla:/var/www/html
      - ./../config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - joomla

  joomla:
    image: joomla:5.0.3-php8.1-fpm-alpine
    restart: always
    environment:
      - JOOMLA_DB_HOST=db
      - JOOMLA_DB_USER=postgres
      - JOOMLA_DB_PASSWORD=mysecretpassword
      - JOOMLA_DB_NAME=db
    volumes:
      - ./joomla:/var/www/html
      - ./../config/php/makedb.php:/makedb.php
    depends_on:
      - db

  db:
    image: postgres:11.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./db:/var/lib/postgresql/data
